//
//  ContentTableRawDifinitions.swift
//  ttune
//
//  Created by Hiromichi Matsushima on 2017/05/17.
//  Copyright © 2017年 Hiromichi Matsushima. All rights reserved.
//

import Foundation

let contentTableRowDifinitions: Dictionary<String, String> = [
    "acknowledgement": "",
    "album": "Album",
    "albumArtist": "Album Artist",
    "albumRating": "",
    "arranger": "",
    "artDirector": "",
    "artist": "Artist",
    "artistID": "",
    "author": "",
    "beatsPerMin": "",
    "bitRate": "",
    "category": "",
    "chapterName": "",
    "chapterNumber": "",
    "composer": "",
    "conductor": "",
    "contentRating": "",
    "copyright": "",
    "coverArt": "",
    "credits": "",
    "dateAtAdd": "",
    "dateAtChange": "",
    "descript": "",
    "director": "",
    "discCompilation": "",
    "discNumber": "",
    "encodedBy": "",
    "encodingTool": "",
    "episodeID": "",
    "episodeNumber": "",
    "eq": "",
    "execProducer": "",
    "genre": "",
    "genreID": "",
    "grouping": "",
    "linerNotes": "",
    "love": "",
    "lyrics": "",
    "onlineExtras": "",
    "originalArtist": "",
    "path": "",
    "performer": "",
    "phonogramRights": "",
    "predefinedGenre": "",
    "producer": "",
    "program": "",
    "publisher": "",
    "recordCompany": "",
    "releaseDate": "",
    "sampleRate": "",
    "season": "",
    "size": "",
    "skips": "",
    "soloist": "",
    "songName": "",
    "sortAlbum": "",
    "sortAlbumArtist": "",
    "sortArtist": "",
    "sortComposer": "",
    "sortProgram": "",
    "soundEngineer": "",
    "thanks": "",
    "time": "Time",
    "title": "Title",
    "trackNumber": "",
    "trackSubTitle": "",
    "userComment": "",
    "userGenre": "",
    "volume": "",
    "year": "",
]

